const cards = [
  {
    id: 1,
    titleImg: './img/title-Serg-Shev',
    name: 'Сергій Шевчук',
    text: {
      type: 'Старший викладач /',
      lightText: 'м. Одеса',
    },
    info: 'Фінансовий аналітик, блогер, постійний гість фінансових оглядів на "Діловому радіо"',
    comment: '“Деньги зарабатываются сидением на месте, а не торговлей”',
    formatText: 'Формат викладання',
    formatIndicate: 'Онлайн',
    experienceText: 'Досвід підготовки трейдерів',
    experienceDate: '7 років',
    graduatesText: 'Кількість випускників',
    graduatesAmount: '126',
    yearText: 'Навчає трейдингу з',
    yearAmount: '2015 року',
  },
  {
    id: 2,
    titleImg: './img/title-Serg-Shev',
    name: 'Сергій Шевчук2',
    text: {
      type: 'Старший викладач /',
      lightText: 'м. Одеса',
    },
    info: 'Фінансовий аналітик, блогер, постійний гість фінансових оглядів на "Діловому радіо"',
    comment: '“Деньги зарабатываются сидением на месте, а не торговлей”',
    formatText: 'Формат викладання',
    formatIndicate: 'Онлайн',
    experienceText: 'Досвід підготовки трейдерів',
    experienceDate: '7 років',
    graduatesText: 'Кількість випускників',
    graduatesAmount: '126',
    yearText: 'Навчає трейдингу з',
    yearAmount: '2015 року',
  },
  {
    id: 3,
    titleImg: './img/title-Serg-Shev',
    name: 'Сергій Шевчук3',
    text: {
      type: 'Старший викладач /',
      lightText: 'м. Одеса',
    },
    info: 'Фінансовий аналітик, блогер, постійний гість фінансових оглядів на "Діловому радіо"',
    comment: '“Деньги зарабатываются сидением на месте, а не торговлей”',
    formatText: 'Формат викладання',
    formatIndicate: 'Онлайн',
    experienceText: 'Досвід підготовки трейдерів',
    experienceDate: '7 років',
    graduatesText: 'Кількість випускників',
    graduatesAmount: '126',
    yearText: 'Навчає трейдингу з',
    yearAmount: '2015 року',
  },
  {
    id: 4,
    titleImg: './img/title-Serg-Shev',
    name: 'Сергій Шевчук4',
    text: {
      type: 'Старший викладач /',
      lightText: 'м. Одеса',
    },
    info: 'Фінансовий аналітик, блогер, постійний гість фінансових оглядів на "Діловому радіо"',
    comment: '“Деньги зарабатываются сидением на месте, а не торговлей”',
    formatText: 'Формат викладання',
    formatIndicate: 'Онлайн',
    experienceText: 'Досвід підготовки трейдерів',
    experienceDate: '7 років',
    graduatesText: 'Кількість випускників',
    graduatesAmount: '126',
    yearText: 'Навчає трейдингу з',
    yearAmount: '2015 року',
  },
]

export default cards
